server:
  host: 192.168.1.52
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: false

  web:
    resources:
      add-mappings: true
  config:
    import:
springdoc:
  swagger-ui:
    enable: true
    tags-sorter: alpha
    path: /swagger-ui.html
jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 604800
app:
  server:
    host: 192.168.1.81
    port: 8080
  gemini:
    api:
      url: ${GEMINI_API_URL}
      key: ${GEMINI_API_KEY}
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}